image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Python dependencies
    command: pip install -r requirements.txt
  - name: Run MySQL and execute DDL.sql
    command: |
      sudo service mysql start
      sleep 5
      mysql -u root -ppass123 < DDL.sql

ports:
  - port: 8080
    onOpen: ignore

onStart:
  - echo "Workspace is ready."